### PR TITLE
add mjml adapter

### PR DESCRIPTION
**Pull request by karimsx**
add support for mjml syntax

### CODE REVIEW

**Comment by TheOpenDevProject** [comment]
Any chance this could get merged, I would greatly benefit from being able to use mjml

**Comment by karimsx** [comment]
no more maitainers?

**Comment by kachar** [comment]
Maybe we can ping them to bring some attention to this PR cc @cdiaz @juandav

**Comment by munchkinpayee** [comment]
+1

**Comment by q1uxu** [comment]
how to use mjml adapter? any examples?

**Pull request merged**
