### PR TITLE
Update to Nest v8

### PR DESCRIPTION
**Pull request by victor192**

### CODE REVIEW

**Comment by omsharp** [comment]
Can anyone, please, approve this PR? I'm in desperate need of it. 
Please!

**Comment by x3r0z** [comment]
Hi, when will merge this PR ??

**Comment by holm** [comment]
It would be really helpful to have this reviewed and merged

**Comment by nelsonBlack** [comment]
could this be merged please

**Comment by michellesanver** [comment]
Also waiting for this. Anything that we can do to help get this merged?

**Comment by VictorAlessander** [comment]
Also waiting for it...

**Comment by yimincai** [comment]
I'm also waiting for it too 🙏

**Comment by sedukhsergey** [comment]
Could you please check this pr?

**Pull request merged**
