### PR TITLE
Fix template resolution

### LINKED ISSUE #733: Template inside sub-folder not found
Version: `"@nestjs-modules/mailer": "^1.6.1",`

I have an email template folder structure like

-src
    - templates
         - user
              - welcome.ejs
              
 In my email send options, I am giving a template: `'user/welcome'`.

In the mailer module configuration, I have the template dir option set as 
`dir: __dirname + '/templates',`

My Nest CLI configuration has

```
  "compilerOptions": {
    "assets": [
      { "include": "**/*.ejs", "outDir": "dist/src" },
      { "include": "**/*.txt", "outDir": "dist/src" },
      { "include": "**/*.png", "outDir": "dist/src" }],
    "watchAssets": true
  }
```

However, the templates are not found.

Another issue, in the `dist` folder, the templates are not under `template ` they are only under `template/user` which means the `outDir` option above in the Nest config did not work.

How can I achieve having templates inside folders?

### PR DESCRIPTION
**Pull request by morpheus-87**
Fixes #733, #684 .

### CODE REVIEW

**Comment by morpheus-87** [comment]
Does this look good, @juandav ?

**Comment by morpheus-87** [comment]
Thanks for merging, @juandav ! Would it be possible to make a release `1.6.2` for this fix?

**Comment by Teebo** [comment]
1.6.2 please

**Comment by thenaim** [comment]
+

**Comment by trongithust** [comment]
@juandav Please release 1.6.2 to apply this

**Pull request merged**
