### PR TITLE
Fix: verifyTransporter logs positive check as a console.error

### PR DESCRIPTION
**Pull request by Maetes**

### CODE REVIEW

**Comment by bodva** [comment]
it is an important change. logging success as an error looks broken.

**Comment by buqiyuan** [comment]
When can the issue be fixed and a new version be released? I have OCD🥹
image

**Comment by juandav** [comment]
@Maetes Can you please resolve the conflicts in order to merge this PR?

**Comment by Maetes** [comment]
Sorry should be fixed, but honestly I think it's not okay to use console.debug rather then a standard log especially gor prod environments...
If you want I change it otherwise ok everything other than error is a improvement

**Pull request closed without merging**
