### PR TITLE
Fix the log type and add a function to verify if all transporters are okay.

### PR DESCRIPTION
**Pull request by GFoniX**
:globe_with_meridians: Adjust the log when a transporter is successfully verified with a 'debug log.' Also, add a function that returns a boolean indicating if all transporters are verified as true.

### CODE REVIEW

**Review by juandav — APPROVED** [review]

**Comment by bodva** [comment]
Is there any information on when it will be released?

**Comment by jaequery** [comment]
this issue has broken our CI/CD, would really appreciate if you can release this fix asap.

**Comment by GFoniX** [comment]
Hey @jaequery, I've made a fix in this PR: https://github.com/nest-modules/mailer/pull/1133. Is it enough to resolve the issues, or do you have any others?

**Comment by jaequery** [comment]
yes, thats the only issue i have. thank you.

**Pull request merged**
